name: Test

on: 
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      
    steps:
      - name: Checkout
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3

      - name: Docker QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3

      - name: Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      # Login to dockerhub if not a fork PR
      - name: Login Dockerhub
        if: ${{ github.event.pull_request == null || !github.event.pull_request.head.repo.fork }}
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          username: notquitenothing
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Login to docker hardened image registry if not a fork PR
      - name: Login Docker Hardened Images Registry
        if: ${{ github.event.pull_request == null || !github.event.pull_request.head.repo.fork }}
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: dhi.io
          username: notquitenothing
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # runs for PRs from forks (skip any registry-backed cache)
      - name: Build Push (fork - no remote cache)
        if: ${{ github.event.pull_request != null && github.event.pull_request.head.repo.fork }}
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        id: docker-build-fork
        with:
          context: .
          file: Dockerfile
          target: build
          platforms: linux/amd64,linux/arm64
          tags: voidauth/voidauth:test
          push: false
          cache-from: |
            type=gha
            type=registry,ref=voidauth/voidauth:latest
            type=registry,ref=voidauth/voidauth:edge

      # runs for PRs from the same repo (or non-PR runs) and uses registry cache
      - name: Build Push (with registry cache)
        if: ${{ github.event.pull_request == null || !github.event.pull_request.head.repo.fork }}
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        id: docker-build
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: voidauth/voidauth:test
          push: false
          cache-from: |
            type=gha
            type=registry,ref=voidauth/voidauth-cache:test
            type=registry,ref=voidauth/voidauth-cache:release
            type=registry,ref=voidauth/voidauth:latest
            type=registry,ref=voidauth/voidauth:edge
          cache-to: type=registry,mode=max,ref=voidauth/voidauth-cache:test
